---
title: "Talks"
---

Bacelar, Sérgio; Gomes, Paulo (2016). Well-being index and Material Living Conditions in Portugal: a ten years' study (2005-2014). *Seminário do Mestrado em Data Analytics - Modelação, Análise de Dados e Sistemas de Apoio à Decisão*, FEP, Univ. Porto,  24 de Novembro 2016  

Bacelar, Sérgio (2016). Statistical evaluation of human wellbeing: The contribution of Statistics Portugal, *CONTROLO 2016, 12th Portuguese Conference on Automatic Control*. Guimarães, 16 September 2016  

Bacelar, Sérgio (2015). The Well-being Index: the weights of different components. How to limit side-effects of acceptable perceptions. *UNECE Seminar on the Role of National Statistical Offices in the production and dissemination of Leading, Composite and Sentiment Indicators*, Geneva, 08/12/2015 - 10/12/2015  

Bacelar, Sérgio; Gomes, Paulo (2015). A new approach to measure Well-being in Portugal (2004-2014). *Seminário do Mestrado em Data Analytics - Modelação, Análise de Dados e Sistemas de Apoio à Decisão*, FEP, Univ. Porto,  19 de Novembro 2015  

Bacelar, Sérgio; Gomes, Paulo (2014). Índice de Bem-estar em Portugal (2004-2013): Contextualização e interpretação dos resultados. *Seminário do Mestrado em Data Analytics - Modelação, Análise de Dados e Sistemas de Apoio à Decisão*, FEP, Univ. Porto,  11 de Dezembro 2014  

Bacelar, Sérgio (2011), “Evolution of retirement: intergenerational cooperation and strong reciprocity”. PhD ‘Research in Progress Workshop (III) at ECSS’11 (*European Conference on Complex Systems*). Vienna, September 14 (abstract accepted).  

Bacelar, Sérgio (2010), “Evolution of social norms in a dynamic scale free network”. *Seminar of the International Doctoral Program in Complexity Sciences* in ISCTE-IUL/FCUL Lisbon, 30 October 2010.  

Bacelar, Sérgio (2010), “Evolution of social norms in a dynamic scale free network”. Young Researchers Session at *ECSS’10 (European Conference on Complex Systems)*. Lisbon, September 15.  

Bacelar, Sérgio (2010), “Evolution of social norms in a dynamic scale free network”. Poster. *ECSS’10 (European Conference on Complex Systems)*. Lisbon, September 15.  

Bacelar, Sérgio (2008), “Investigação social e análise secundária de dados: as estatísticas oficiais como objectos socialmente construídos”. Conferência em 31/05/08 no *Curso de Doutoramento em Ciências da Educação na Faculdade de Psicologia e Ciências da Educação* da Universidade do Porto.  

Bacelar, Sérgio (2007), Evolução da população e estrutura familiar na Região Norte nos últimos 15 anos: mudança e continuidade. Comunicação apresentada a 5 de Novembro de 2007 na apresentação pública do projecto financiado pela FCT, "A Região Norte de Portugal: Dinâmicas de Mudança Social e Recentes Processos de Desenvolvimento" (Instituto de Sociologia, Faculdade de Letras da U. Porto, 2006-2007) na Faculdade de Letras da Universidade do Porto.  

Bacelar, Sérgio e Fernandes, Paula Guilhermina (2007), Extending working lives - Denmark and Portugal: on target for divergent reasons , Comunicação apresentada na *VIII Conferência da Associação Europeia de Sociologia, Conflict, Citizenship and Civil Society*, Glasgow, 3-6 de Setembro de 2007.  

Bolseiro do Programa Sócrates-Erasmus e realização nesse âmbito de um Seminário em Abril de 2007 na Katholische Fachhochschule Freiburg: Sérgio Bacelar & Paula Guilhermina Fernandes, “Being a social worker in Portugal and Germany – Commonalities and differences”.  

Bolseiro do Programa Sócrates-Erasmus e realização nesse âmbito de um Seminário em 2006 na Danish School of Social Work (Aarhus - Dinamarca); intitulado “On Target, By the Wrong Reasons: Extending Working Lives in Portugal. (Social Work and Social Policies for older workers in a southern European country)”.  

Bacelar, Sérgio (2006), “Explicação, Análise Causal e Mecanismos Sociais”. Conferência em 20/3/06 na Faculdade de Letras da Universidade do Porto.  

Bacelar, Sérgio (2004), Os idosos em Portugal: ameaças e novas oportunidades, comunicação apresentada nas *I Jornadas “Idade e qualidade de vida"*, Universidade Portucalense Infante D.Henrique, Porto, 19 de Maio de 2004  

Gisela Chicau, Fernanda Figueiredo, Pedro Campos, Sérgio Bacelar e Margarida Aboim Inglez (2004), Avaliação da Incidência de Armillaria Spp. em três Concelhos da Região de Entre Douro e Minho, *4º Congresso da Sociedade Portuguesa de Fitopatologia*, Faro, 4 a 6 de Fevereiro de 2004.  

Bacelar, Sérgio; Gomes, Paulo (1994), 'Tipologia sócio-demográfica dos concelhos da Região Norte', comunicação apresentada nas *I Jornadas de Classificação e Análise de Dados*, Lisboa;  

Bacelar Sérgio (1982), 'Caricatura e Representação Política', comunicação apresentada nas *Jornadas de Comunicação Social*, Instituto Superior de Ciências do Trabalho e da Empresa. Lisboa.  

## Conferences organization

Bacelar, Sérgio *et al.* (2012) Co-organizer of ['Complexity in the Real-World - from policy intelligence to intelligent policy'](http://ecss2012.ulb.ac.be/satellite.php). Satellite meeting of the *European Conference on Complex Systems (ECCS '12')*. Brussels, September 5-6, 2012. 